CREATE TABLE IF NOT EXISTS default.flows_raw
(
    `date` Date,
    `time_inserted_ns` DateTime64(3) CODEC(DoubleDelta, ZSTD(1)),
    `time_received_ns` DateTime64(9) CODEC(DoubleDelta, ZSTD(1)),
    `time_flow_start_ns` DateTime64(3) CODEC(DoubleDelta, ZSTD(1)),
    `sequence_num` UInt32,
    `sampling_rate` UInt64,
    `sampler_address` FixedString(16),
    `src_addr` FixedString(16),
    `dst_addr` FixedString(16),
    `etype` UInt32,
    `proto` UInt32 CODEC(T64, ZSTD(1)),
    `src_port` UInt32 CODEC(T64, ZSTD(1)),
    `dst_port` UInt32 CODEC(T64, ZSTD(1)),
    `src_vlan` UInt16 CODEC(T64, ZSTD(1)),
    `dst_vlan` UInt16 CODEC(T64, ZSTD(1)),
    `vlan_id` UInt32,
    `bytes` UInt64 CODEC(T64, ZSTD(1)),
    `packets` UInt64 CODEC(T64, ZSTD(1)),
    `src_asn` UInt32 DEFAULT 0 CODEC(T64, ZSTD(1)),
    `dst_asn` UInt32 DEFAULT 0 CODEC(T64, ZSTD(1)),
    `direction` LowCardinality(String) DEFAULT 'unknown',
    `src_kind` LowCardinality(String) DEFAULT 'unknown',
    `dst_kind` LowCardinality(String) DEFAULT 'unknown',
    `src_label` LowCardinality(String) DEFAULT '',
    `dst_label` LowCardinality(String) DEFAULT '',
    `src_operator` LowCardinality(String) DEFAULT '',
    `dst_operator` LowCardinality(String) DEFAULT '',
    `src_attachment_kind` LowCardinality(String) DEFAULT 'unknown',
    `dst_attachment_kind` LowCardinality(String) DEFAULT 'unknown',
    `src_attachment_boundary` LowCardinality(String) DEFAULT 'unknown',
    `dst_attachment_boundary` LowCardinality(String) DEFAULT 'unknown',
    `src_attachment_label` LowCardinality(String) DEFAULT '',
    `dst_attachment_label` LowCardinality(String) DEFAULT '',
    `src_attachment_operator` LowCardinality(String) DEFAULT '',
    `dst_attachment_operator` LowCardinality(String) DEFAULT '',
    `src_endpoint_scope` LowCardinality(String) DEFAULT 'unknown',
    `dst_endpoint_scope` LowCardinality(String) DEFAULT 'unknown',
    `src_endpoint_source` LowCardinality(String) DEFAULT 'unknown',
    `dst_endpoint_source` LowCardinality(String) DEFAULT 'unknown',
    `src_network_name` String DEFAULT '',
    `dst_network_name` String DEFAULT '',
    `src_network_role` LowCardinality(String) DEFAULT '',
    `dst_network_role` LowCardinality(String) DEFAULT '',
    `src_role` LowCardinality(String) DEFAULT '',
    `dst_role` LowCardinality(String) DEFAULT '',
    `src_entity` LowCardinality(String) DEFAULT '',
    `dst_entity` LowCardinality(String) DEFAULT '',
    `src_client` LowCardinality(String) DEFAULT '',
    `dst_client` LowCardinality(String) DEFAULT '',
    `source_id` LowCardinality(String) DEFAULT 'xdp-default',
    `src_mac` FixedString(6) DEFAULT '',
    `dst_mac` FixedString(6) DEFAULT '',
    `in_if` UInt32 DEFAULT 0,
    `out_if` UInt32 DEFAULT 0,
    `tcp_flags` UInt8 DEFAULT 0,
    `ip_ttl` UInt8 DEFAULT 0,
    `ip_tos` UInt8 DEFAULT 0,
    INDEX idx_obs_src_vlan src_vlan TYPE set(0) GRANULARITY 4,
    INDEX idx_obs_dst_vlan dst_vlan TYPE set(0) GRANULARITY 4,
    INDEX idx_obs_src_port src_port TYPE bloom_filter(0.01) GRANULARITY 4,
    INDEX idx_obs_dst_port dst_port TYPE bloom_filter(0.01) GRANULARITY 4,
    INDEX idx_src_client src_client TYPE bloom_filter(0.01) GRANULARITY 4,
    INDEX idx_dst_client dst_client TYPE bloom_filter(0.01) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY date
ORDER BY time_received_ns
TTL date + toIntervalDay(6)
SETTINGS index_granularity = 8192, max_bytes_to_merge_at_max_space_in_pool = 8589934592;
