-- Apply new Network Analytics schema after cleanup_old_classification.sql.
--
-- Order:
--   1. cleanup_old_classification.sql
--   2. flows_raw_extensions.sql
--   2b. net_flow_sources.sql + flows_raw_source_id.sql (when enabling source tracking)
--   2c. geo_country.sql + geoloaderd (geo_country_dict, asn_registry_enriched)
--   3. net_entities.sql
--   4. net_l3_prefixes.sql
--   5. net_l2_vlans.sql
--   6. traffic_direction_1m.sql
--   7. traffic_role_1m.sql
--   8. traffic_entity_1m.sql
--   9. traffic_vlan_1m.sql
--  10. port_services.sql
--  11. traffic_protocol_1m.sql
--  12. traffic_service_1m.sql
--  13. traffic_unknown_port_1m.sql
--  14. traffic_country_1m.sql
--  15. traffic_dashboard_1m.sql
--  16. traffic_dashboard_1d.sql
--  17. net_reports.sql
--
-- Example:
--   for f in deploy/clickhouse/cleanup_old_classification.sql \
--            deploy/clickhouse/flows_raw_extensions.sql \
--            deploy/clickhouse/net_entities.sql \
--            deploy/clickhouse/net_l3_prefixes.sql \
--            deploy/clickhouse/net_l2_vlans.sql \
--            deploy/clickhouse/traffic_direction_1m.sql \
--            deploy/clickhouse/traffic_role_1m.sql \
--            deploy/clickhouse/traffic_entity_1m.sql \
--            deploy/clickhouse/traffic_vlan_1m.sql \
--            deploy/clickhouse/port_services.sql \
--            deploy/clickhouse/traffic_protocol_1m.sql \
--            deploy/clickhouse/traffic_service_1m.sql \
--            deploy/clickhouse/geo_country.sql \
--            deploy/clickhouse/traffic_unknown_port_1m.sql \
--            deploy/clickhouse/traffic_country_1m.sql \
--            deploy/clickhouse/traffic_dashboard_1m.sql \
--            deploy/clickhouse/traffic_dashboard_1d.sql \
--            deploy/clickhouse/net_reports.sql; do
--     clickhouse-client --host HOST --user USER --password PASS --multiquery < "$f"
--   done
