-- Network analytics schema is canonical in deploy/schema/.
--
-- Fresh install:
--   ./deploy/schema/apply.sh
--
-- Existing DB that still has pre-analytics objects:
--   1. deploy/clickhouse/cleanup_old_classification.sql
--   2. deploy/clickhouse/flows_raw_extensions.sql
--   3. deploy/clickhouse/flows_raw_mac.sql
--   4. deploy/schema/apply.sh 50_net 60_traffic
--   5. deploy/clickhouse/detach_traffic_mvs.sql
--
-- Rollups: grapes-worker (scripts/traffic_rollup_async.py), not sync MVs.
-- See docs/CLICKHOUSE_DB_SETUP_RUNBOOK.md.
SELECT 'use deploy/schema/apply.sh instead of this file';
