-- BGP prefix -> origin ASN lookup for traffic enrichment.
--
-- Apply once, then run scripts/rebuild_bgp_origin_asn.py periodically.
-- The script fills bgp_prefix_origin_current from bmp_route_events and creates
-- / reloads bgp_origin_asn_dict as an IP_TRIE dictionary.

CREATE TABLE IF NOT EXISTS default.bgp_prefix_origin_current_staging
(
    prefix       String,
    family       UInt8,
    origin_asn   UInt32,
    peer_asn     UInt32,
    active_paths UInt32,
    last_ts      DateTime64(6, 'UTC'),
    source       LowCardinality(String),
    snapshot_ts  DateTime
)
ENGINE = MergeTree
ORDER BY (family, prefix)
SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS default.bgp_prefix_origin_current
(
    prefix       String,
    family       UInt8,
    origin_asn   UInt32,
    peer_asn     UInt32,
    active_paths UInt32,
    last_ts      DateTime64(6, 'UTC'),
    source       LowCardinality(String),
    snapshot_ts  DateTime
)
ENGINE = MergeTree
ORDER BY (family, prefix)
SETTINGS index_granularity = 8192;

-- Dictionary DDL is generated by scripts/rebuild_bgp_origin_asn.py so its
-- SOURCE can use ClickHouse-internal credentials/endpoints, for example:
--
--   loader -> 95.215.1.30:6124
--   ClickHouse dictionary source -> 127.0.0.1:9000
