CREATE TABLE IF NOT EXISTS default.collector_health_snapshots
(
    `ts` DateTime64(3, 'UTC'),
    `collector_id` String,
    `source_id` String,
    `daemon` LowCardinality(String),
    `hostname` String DEFAULT hostName(),
    `iface` String DEFAULT '',
    `xdp_total_packets` UInt64 DEFAULT 0,
    `xdp_total_bytes` UInt64 DEFAULT 0,
    `xdp_map_full` UInt64 DEFAULT 0,
    `xdp_parse_errors` UInt64 DEFAULT 0,
    `xdp_non_ip_pass` UInt64 DEFAULT 0,
    `nic_rx_packets` UInt64 DEFAULT 0,
    `nic_rx_bytes` UInt64 DEFAULT 0,
    `nic_rx_dropped` UInt64 DEFAULT 0,
    `nic_rx_errors` UInt64 DEFAULT 0,
    `nic_rx_missed` UInt64 DEFAULT 0,
    `nic_rx_fifo_errors` UInt64 DEFAULT 0,
    `phy_rx_packets` UInt64 DEFAULT 0,
    `phy_rx_discards` UInt64 DEFAULT 0,
    `phy_counter_source` LowCardinality(String) DEFAULT '',
    `datagrams` UInt64 DEFAULT 0,
    `records_parsed` UInt64 DEFAULT 0,
    `receiver_parse_errors` UInt64 DEFAULT 0,
    `udp_queue_drops` UInt64 DEFAULT 0,
    `ch_mode` LowCardinality(String) DEFAULT '',
    `records_queued` UInt64 DEFAULT 0,
    `records_written` UInt64 DEFAULT 0,
    `records_spooled` UInt64 DEFAULT 0,
    `records_acked` UInt64 DEFAULT 0,
    `flow_packets_queued` UInt64 DEFAULT 0,
    `flow_bytes_queued` UInt64 DEFAULT 0,
    `flow_packets_written` UInt64 DEFAULT 0,
    `flow_bytes_written` UInt64 DEFAULT 0,
    `flow_packets_spooled` UInt64 DEFAULT 0,
    `flow_bytes_spooled` UInt64 DEFAULT 0,
    `flow_packets_acked` UInt64 DEFAULT 0,
    `flow_bytes_acked` UInt64 DEFAULT 0,
    `insert_errs` UInt64 DEFAULT 0,
    `ch_queue_drops` UInt64 DEFAULT 0,
    `lag_segments` Int64 DEFAULT 0,
    `drainer_progress_age_sec` Float64 DEFAULT 0,
    `spool_corruption_frames` UInt64 DEFAULT 0,
    `spool_corruption_bytes` UInt64 DEFAULT 0,
    `flow_rows_excluded` UInt64 DEFAULT 0,
    `flow_packets_excluded` UInt64 DEFAULT 0,
    `flow_bytes_excluded` UInt64 DEFAULT 0,
    `exclusion_rules` UInt32 DEFAULT 0,
    `nf_records_out` UInt64 DEFAULT 0,
    `nf_packets_out` UInt64 DEFAULT 0,
    `nf_bytes_out` UInt64 DEFAULT 0,
    `nf_send_errs` UInt64 DEFAULT 0,
    `nf_dsts` String DEFAULT '',
    `nf_socket_drops` UInt64 DEFAULT 0,
    `nf_socket_observed` UInt8 DEFAULT 0,
    `pipeline_stages` Array(LowCardinality(String)) DEFAULT [],
    `status` LowCardinality(String) DEFAULT 'ok',
    `status_reasons` Array(String) DEFAULT []
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(ts)
ORDER BY (source_id, ts)
TTL toDateTime(ts) + toIntervalDay(90)
SETTINGS index_granularity = 8192;
